export const subjects = [
  {
    id: "science",
    name: "Science",
    description: "Physics, Chemistry, Biology",
    icon: "Flask",
    color: "from-green-500 to-emerald-600",
    chapters: [
      { id: 1, name: "Chemical Reactions and Equations", topics: 12 },
      { id: 2, name: "Acids, Bases and Salts", topics: 10 },
      { id: 3, name: "Metals and Non-metals", topics: 14 },
      { id: 4, name: "Carbon and its Compounds", topics: 11 },
      { id: 5, name: "Life Processes", topics: 15 },
      { id: 6, name: "Control and Coordination", topics: 8 },
      { id: 7, name: "How do Organisms Reproduce?", topics: 10 },
      { id: 8, name: "Heredity and Evolution", topics: 9 },
      { id: 9, name: "Light - Reflection and Refraction", topics: 12 },
      { id: 10, name: "Human Eye and Colourful World", topics: 8 },
      { id: 11, name: "Electricity", topics: 14 },
      { id: 12, name: "Magnetic Effects of Electric Current", topics: 10 },
      { id: 13, name: "Our Environment", topics: 6 },
    ],
  },
  {
    id: "maths",
    name: "Mathematics",
    description: "Algebra, Geometry, Statistics",
    icon: "Calculator",
    color: "from-blue-500 to-indigo-600",
    chapters: [
      { id: 1, name: "Real Numbers", topics: 8 },
      { id: 2, name: "Polynomials", topics: 10 },
      { id: 3, name: "Pair of Linear Equations in Two Variables", topics: 12 },
      { id: 4, name: "Quadratic Equations", topics: 10 },
      { id: 5, name: "Arithmetic Progressions", topics: 9 },
      { id: 6, name: "Triangles", topics: 11 },
      { id: 7, name: "Coordinate Geometry", topics: 8 },
      { id: 8, name: "Introduction to Trigonometry", topics: 10 },
      { id: 9, name: "Some Applications of Trigonometry", topics: 6 },
      { id: 10, name: "Circles", topics: 8 },
      { id: 11, name: "Areas Related to Circles", topics: 7 },
      { id: 12, name: "Surface Areas and Volumes", topics: 10 },
      { id: 13, name: "Statistics", topics: 9 },
      { id: 14, name: "Probability", topics: 7 },
    ],
  },
  {
    id: "sst",
    name: "Social Science",
    description: "History, Geography, Civics, Economics",
    icon: "Globe",
    color: "from-orange-500 to-red-600",
    chapters: [
      { id: 1, name: "The Rise of Nationalism in Europe", topics: 8 },
      { id: 2, name: "Nationalism in India", topics: 10 },
      { id: 3, name: "The Making of a Global World", topics: 9 },
      { id: 4, name: "The Age of Industrialisation", topics: 8 },
      { id: 5, name: "Print Culture and the Modern World", topics: 7 },
      { id: 6, name: "Resources and Development", topics: 10 },
      { id: 7, name: "Forest and Wildlife Resources", topics: 6 },
      { id: 8, name: "Water Resources", topics: 7 },
      { id: 9, name: "Agriculture", topics: 9 },
      { id: 10, name: "Minerals and Energy Resources", topics: 8 },
      { id: 11, name: "Manufacturing Industries", topics: 7 },
      { id: 12, name: "Power Sharing", topics: 6 },
      { id: 13, name: "Federalism", topics: 7 },
      { id: 14, name: "Democracy and Diversity", topics: 5 },
      { id: 15, name: "Development", topics: 6 },
      { id: 16, name: "Sectors of the Indian Economy", topics: 8 },
      { id: 17, name: "Money and Credit", topics: 7 },
      { id: 18, name: "Globalisation and the Indian Economy", topics: 6 },
    ],
  },
  {
    id: "english",
    name: "English",
    description: "Literature, Grammar, Writing",
    icon: "BookOpen",
    color: "from-purple-500 to-violet-600",
    chapters: [
      { id: 1, name: "A Letter to God", topics: 5 },
      { id: 2, name: "Nelson Mandela: Long Walk to Freedom", topics: 6 },
      { id: 3, name: "Two Stories about Flying", topics: 5 },
      { id: 4, name: "From the Diary of Anne Frank", topics: 6 },
      { id: 5, name: "The Hundred Dresses - I", topics: 4 },
      { id: 6, name: "The Hundred Dresses - II", topics: 4 },
      { id: 7, name: "Glimpses of India", topics: 6 },
      { id: 8, name: "Mijbil the Otter", topics: 5 },
      { id: 9, name: "Madam Rides the Bus", topics: 5 },
      { id: 10, name: "The Sermon at Benares", topics: 4 },
      { id: 11, name: "The Proposal", topics: 5 },
      { id: 12, name: "Dust of Snow & Fire and Ice (Poems)", topics: 4 },
      { id: 13, name: "A Tiger in the Zoo (Poem)", topics: 3 },
      { id: 14, name: "Grammar & Writing Skills", topics: 15 },
    ],
  },
  {
    id: "hindi",
    name: "Hindi",
    description: "Kshitij, Kritika, Vyakaran",
    icon: "Languages",
    color: "from-pink-500 to-rose-600",
    chapters: [
      { id: 1, name: "सूरदास के पद", topics: 5 },
      { id: 2, name: "राम-लक्ष्मण-परशुराम संवाद", topics: 6 },
      { id: 3, name: "सवैया और कवित्त", topics: 5 },
      { id: 4, name: "आत्मकथ्य", topics: 4 },
      { id: 5, name: "उत्साह और अट नहीं रही", topics: 4 },
      { id: 6, name: "यह दंतुरहित मुस्कान और फसल", topics: 5 },
      { id: 7, name: "छाया मत छूना", topics: 4 },
      { id: 8, name: "कन्यादान", topics: 4 },
      { id: 9, name: "संगतकार", topics: 4 },
      { id: 10, name: "नेताजी का चश्मा", topics: 5 },
      { id: 11, name: "बालगोबिन भगत", topics: 5 },
      { id: 12, name: "लखनवी अंदाज़", topics: 4 },
      { id: 13, name: "मानवीय करुणा की दिव्य चमक", topics: 5 },
      { id: 14, name: "एक कहानी यह भी", topics: 5 },
      { id: 15, name: "व्याकरण (Grammar)", topics: 12 },
    ],
  },
];

export const features = [
  {
    title: "High-Quality Notes",
    description: "Well-structured chapter-wise notes prepared by expert teachers",
    icon: "FileText",
  },
  {
    title: "Sample Papers",
    description: "Practice with latest pattern sample papers for Board 2025",
    icon: "ClipboardList",
  },
  {
    title: "Previous Year Questions",
    description: "Year-wise PYQs from 2015-2024 with detailed solutions",
    icon: "History",
  },
  {
    title: "Practice Tests",
    description: "MCQ tests and short answer practice with instant scoring",
    icon: "Target",
  },
  {
    title: "Mind Maps",
    description: "Visual learning aids for quick revision and concept clarity",
    icon: "Brain",
  },
  {
    title: "Formula Sheets",
    description: "Quick reference sheets for important formulas and concepts",
    icon: "Calculator",
  },
];

export const samplePapers = [
  { id: 1, subject: "Science", year: 2025, type: "Sample Paper Set 1" },
  { id: 2, subject: "Science", year: 2025, type: "Sample Paper Set 2" },
  { id: 3, subject: "Maths", year: 2025, type: "Sample Paper Set 1" },
  { id: 4, subject: "Maths", year: 2025, type: "Sample Paper Set 2" },
  { id: 5, subject: "SST", year: 2025, type: "Sample Paper Set 1" },
  { id: 6, subject: "English", year: 2025, type: "Sample Paper Set 1" },
  { id: 7, subject: "Hindi", year: 2025, type: "Sample Paper Set 1" },
];

export const pyqs = [
  { id: 1, subject: "Science", year: 2024 },
  { id: 2, subject: "Science", year: 2023 },
  { id: 3, subject: "Science", year: 2022 },
  { id: 4, subject: "Maths", year: 2024 },
  { id: 5, subject: "Maths", year: 2023 },
  { id: 6, subject: "Maths", year: 2022 },
  { id: 7, subject: "SST", year: 2024 },
  { id: 8, subject: "SST", year: 2023 },
  { id: 9, subject: "English", year: 2024 },
  { id: 10, subject: "Hindi", year: 2024 },
];
